### ISSUE TITLE
ValueError: Substring not found

### ISSUE THREAD

**Issue by Lamiiine** [unl1kely/ifa-tcf-catcher#5]
When registration opened, this is what your code returns
```shell
Traceback (most recent call last):
  File "__init__.py", line 150, in <module>
    main()
  File "__init__.py", line 124, in main
    instance = IFA(code)
  File "__init__.py", line 85, in __init__
    jsData = self.code[self.code.index("var defaultEvents")+21:self.code.index("console.log(defaultEvents)")-7]
ValueError: substring not found
```

**Comment by unl1kely** [comment]
This is weird.
Can you send me a screenshot from the website after you log in with your
account ?

**Comment by Lamiiine** [comment]
IF's website is down for the moment. It appears the site was down with no time slots open. Will keep you posted.
Also, did you get any feedback from anyone who managed to reserve a spot with your script? and how what if the payment box is grey and not white! what happens in this case?

**Comment by unl1kely** [comment]
My script doesn't reserve RDVs, it only notifies the user when some RDV
spot is available AND only if payment dates are available.
No JSON response means there are spots but with no payment dates (which is
useless).

I named this repo "catcher" because I tried to improve the script and make
it reserve automatically but it takes time to test the codes. And since the
RDVs don't last for a long time, I could not do it, unfortunately.
You have to know what type of request to send, to which link, the headers,
and also how to get the payment dates, how to include them in the headers
with the right format.

Now that I already named it, changing the name would cause unwanted
problems according to GitHub.
